require 'vigilo'
require 'vigilo/adapters/fsevents'
require 'mongoid'
require 'active_support/configurable'

require 'maleable/version'
require 'maleable/action'
require 'maleable/base'
require 'maleable/runner'
require 'maleable/file'
